<?php

namespace AppBundle\Entity;

/**
 * antiguedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class antiguedadRepository extends \Doctrine\ORM\EntityRepository
{
}
