<?php

namespace AppBundle\Entity;

/**
 * DonadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonadorRepository extends \Doctrine\ORM\EntityRepository
{
}
