<?php

namespace AppBundle\Entity;

/**
 * ProgramaConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaConceptoRepository extends \Doctrine\ORM\EntityRepository
{
}
