<?php

namespace AppBundle\Entity;

/**
 * ProgramaSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
